# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1344c70e0aafabd3eccb6583ec4239822609c0de989cea3930184f8f8c4f96a0e21d69d9ab7a0e8516a7048ecdcf834f5b066e1947b7c07f4e75f70cb835732

test:
  secret_key_base: dfb3f4ff7a387925bb98dc8769816c70e091690a50866856c08d104e0957170e64aaea5cb9925d3056e57694d262bad22e22d07fa40b931073c8e0f47abdd9f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
